Use bash "set -xe" in jenkins build script

diff --git a/buildscripts/jenkins-build b/buildscripts/jenkins-build
--- a/buildscripts/jenkins-build
+++ b/buildscripts/jenkins-build
@@ -17,6 +17,9 @@
 #     directory as buildscripts/jenkins-build
 #
 
+# Set options to echo every command and exit on error
+set -xe
+
 # Require a version of Python to be selected
 if [ "${PYTHON_VERSION}" == "" ]; then
  echo You must select a Python version with the PYTHON_VERSION variable.
@@ -40,17 +43,22 @@ rm -rf build
 # Get libdynd into the libraries subdirectory
 # TODO: Build libdynd in a separate jenkins project,
 #       and use its build artifact here.
-./buildscripts/checkout_libdynd.sh || exit 1
+rm -rf libraries
+mkdir libraries
+pushd libraries
+git clone https://github.com/ContinuumIO/libdynd.git
+popd
 
 # Make sure binstar is installed in the main environment
 echo Updating binstar...
-~/anaconda/bin/conda install --yes binstar || exit 1
+~/anaconda/bin/conda install --yes binstar
 ~/anaconda/bin/binstar --version
 
 # Use conda to create a conda environment of the required
 # python version and containing the dependencies.
 export PYENV_PREFIX=${WORKSPACE}/build/pyenv
-~/anaconda/bin/python ./buildscripts/create_conda_pyenv_retry.py ${PYTHON_VERSION} ${PYENV_PREFIX} || exit 1
+rm -rf ${PYENV_PREFIX}
+~/anaconda/bin/conda create --yes -p ${PYENV_PREFIX} python=${PYTHON_VERSION} cython scipy nose
 export PATH=${PYENV_PREFIX}/bin:${PATH}
 
 if [ -f "${PYENV_PREFIX}/bin/python" ]; then
@@ -74,21 +82,16 @@ export EXTRA="-DDYND_BUILD_TESTS=OFF ${EXTRA}"
 
 # Create a fresh makefile with cmake, and do the build/install
 cd build
-echo cmake ${EXTRA} \
-      -DCMAKE_INSTALL_PREFIX=${PYENV_PREFIX} \
-      -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
-      -DCMAKE_C_COMPILER=${CC} \
-      -DCMAKE_CXX_COMPILER=${CXX} ..
 cmake ${EXTRA} \
       -DCMAKE_INSTALL_PREFIX=${PYENV_PREFIX} \
       -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
       -DCMAKE_C_COMPILER=${CC} \
-      -DCMAKE_CXX_COMPILER=${CXX} .. || exit 1
-make VERBOSE=1 || exit 1
-make install || exit 1
+      -DCMAKE_CXX_COMPILER=${CXX} ..
+make VERBOSE=1
+make install
 
 # Run the unit tests
-${PYTHON_EXECUTABLE} -c 'import dynd;dynd.test(xunitfile="../test_results.xml", exit=1)' || exit 1
+${PYTHON_EXECUTABLE} -c 'import dynd;dynd.test(xunitfile="../test_results.xml", exit=1)'
 
 # Retrieve the version number
 export PYDYND_VERSION=`${PYTHON_EXECUTABLE} -c 'import dynd;print(dynd.__version__)'`
@@ -115,9 +118,9 @@ else
 fi
 
 # Create a conda package from the build
-~/anaconda/bin/conda package -p ${PYENV_PREFIX} --pkg-name=dynd-python --pkg-version=${PYDYND_VERSION} || exit 1
+~/anaconda/bin/conda package -p ${PYENV_PREFIX} --pkg-name=dynd-python --pkg-version=${PYDYND_VERSION}
 
 # Upload the package to binstar
-~/anaconda/bin/binstar -t ${BINSTAR_AUTH} upload --force dynd-python*.tar.bz2 || exit 1
+~/anaconda/bin/binstar -t ${BINSTAR_AUTH} upload --force dynd-python*.tar.bz2
 
 cd ..
